version: "3.8"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
