export const SPAM_KEYWORDS = {
	financialAndMonetary: [
		"earn",
		"discount",
		"pure profit",
		"credit",
		"investment",
		"loan",
		"save",
		"million dollars",
		"financial freedom",
		"get paid",
		"bankruptcy",
		"refinance",
		"money back",
		"debt",
		"extra income",
		"no fees",
		"best rates",
		"cash bonus",
		"extra cash",
		"easy money",
		"penny stocks",
		"wealth",
		"no hidden charges",
		"no hidden costs",
		"be your own boss",
		"unsecured credit",
		"lower interest rates",
		"accept credit cards",
		"best mortgage rates",
		"cashback",
	],
	urgencyAndScarcity: [
		"limited offer",
		"act now",
		"exclusive",
		"urgent",
		"immediate",
		"deadline",
		"only a few left",
		"hurry",
		"last chance",
		"today only",
		"final hours",
		"while supplies last",
		"one time",
		"expires",
		"never again",
		"don't miss",
		"rush",
		"time-sensitive",
		"offer expires",
		"instant access",
		"closing soon",
		"final call",
		"once in a lifetime",
		"limited time",
		"now or never",
		"flash sale",
		"countdown",
		"last minute deal",
		"rare opportunity",
		"ends tonight",
	],
	marketingAndSales: [
		"offer",
		"buy now",
		"free",
		"serious bargain",
		"best price",
		"deal",
		"special promotion",
		"winner",
		"discount",
		"special offer",
		"giveaway",
		"bonus",
		"cheap",
		"trial",
		"free gift",
		"prize",
		"coupon",
		"clearance",
		"sale",
		"all new",
		"no obligation",
		"limited time offer",
		"exclusive deal",
		"save big",
		"bargain hunter's dream",
		"hurry, while supplies last",
		"risk-free",
		"act now",
		"once-in-a-lifetime",
		"mega sale",
	],
	healthAndPharmaceuticals: [
		"viagra",
		"weight loss",
		"pharmaceuticals",
		"supplement",
		"herbal",
		"cure",
		"medicine",
		"natural",
		"pills",
		"drugs",
		"diet",
		"remedy",
		"treatment",
		"healthcare",
		"therapy",
		"prescription",
		"pharmacy",
		"body",
		"healing",
		"wellness",
		"detox",
		"clinic",
		"vaccine",
		"organic",
		"fitness",
		"nutrition",
		"therapeutics",
		"supplements",
		"well-being",
		"antioxidant",
	],
	personalAndConfidential: [
		"private",
		"confidential",
		"winner",
		"selected",
		"guaranteed",
		"personal",
		"secret",
		"exclusive access",
		"membership",
		"you have been chosen",
		"claim",
		"beneficiary",
		"award",
		"pre-approved",
		"eligible",
		"certified",
		"not shared",
		"sensitive",
		"protection",
		"verified",
		"urgent",
		"limited time",
		"priority access",
		"restricted information",
		"top secret",
		"special offer",
		"confidential deal",
		"privileged",
		"exclusive rights",
		"secure claim",
	],
	exaggeratedClaims: [
		"miracle",
		"amazing",
		"incredible",
		"magic",
		"once in a lifetime",
		"revolutionary",
		"sensational",
		"unbelievable",
		"phenomenal",
		"fantastic",
		"life-changing",
		"unmatched",
		"breakthrough",
		"top-notch",
		"stunning",
		"spectacular",
		"unparalleled",
		"outstanding",
		"extraordinary",
		"supreme",
		"astounding",
		"remarkable",
		"unprecedented",
		"jaw-dropping",
		"breathtaking",
		"groundbreaking",
		"mind-blowing",
		"majestic",
		"unrivaled",
		"ultimate",
	],
	spammyPhrases: [
		"dear friend",
		"congratulations",
		"you have been chosen",
		"hello!",
		"greetings",
		"dear beneficiary",
		"good news",
		"special for you",
		"attention",
		"hi there",
		"to whom it may concern",
		"special invitation",
		"dear valued customer",
		"exclusive invitation",
		"dear sir/madam",
		"good day",
		"friendly reminder",
		"welcome",
		"important notice",
		"dear [name]",
		"urgent response required",
		"exciting opportunity",
		"limited time offer",
		"you're a winner!",
		"act now!",
		"confidential proposal",
		"exclusive deal",
		"fantastic offer",
		"priority access",
		"selected specially",
	],
	suspiciousLinks: [
		"download now",
		"click here",
		"attachment",
		"unsubscribe here",
		"link",
		"see attachment",
		"exclusive download",
		"open this",
		"click to view",
		"access here",
		"file attached",
		"free download",
		"click below",
		"video inside",
		"document",
		"view now",
		"install now",
		"activate link",
		"preview file",
		"access file",
		"download attachment",
		"exclusive link",
		"open file",
		"click to open",
		"secure download",
		"attached document",
		"downloadable content",
		"access attachment",
		"view attachment",
		"open attachment",
	],
	additionalTriggers: [
		"#1",
		"100% more",
		"100% free",
		"100% satisfied",
		"additional income",
		"be your own boss",
		"best price",
		"big bucks",
		"billion",
		"cash bonus",
		"cents on the dollar",
		"consolidate debt",
		"double your cash",
		"double your income",
		"earn extra cash",
		"earn money",
		"eliminate bad credit",
		"extra cash",
		"extra income",
		"expect to earn",
		"fast cash",
		"financial freedom",
		"free access",
		"free consultation",
		"free gift",
		"free hosting",
		"free info",
		"free investment",
		"free membership",
		"free money",
		"free preview",
		"free quote",
		"free trial",
		"full refund",
		"get out of debt",
		"get paid",
		"giveaway",
		"guaranteed",
		"increase sales",
		"increase traffic",
		"incredible deal",
		"lower rates",
		"lowest price",
		"make money",
		"million dollars",
		"miracle",
		"money back",
		"once in a lifetime",
		"one time",
		"pennies a day",
		"potential earnings",
		"prize",
		"promise",
		"pure profit",
		"risk-free",
		"satisfaction guaranteed",
		"save big money",
		"save up to",
		"special promotion",
	],
};

export const getAllSpamKeywords = (): string[] => {
	return Object.values(SPAM_KEYWORDS)
		.flat()
		.map((keyword) => keyword.toLowerCase());
};

export const containsSpamKeywords = (text: string): boolean => {
	const normalizedText = text.toLowerCase();
	return getAllSpamKeywords().some((keyword) =>
		normalizedText.includes(keyword.toLowerCase()),
	);
};

export const findSpamKeywords = (text: string): string[] => {
	const normalizedText = text.toLowerCase();
	return getAllSpamKeywords().filter((keyword) =>
		normalizedText.includes(keyword.toLowerCase()),
	);
};
