
name: Deploy to Main

on:
  push:
    branches:
      - main

env:
  REGION: us-west1
  SERVICE: datamax-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "^3.11"

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        id: "auth"
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_API_KEY_BASE64 }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build -t ${{ env.SERVICE }} .

      - name: Build image
        run: docker tag ${{ env.SERVICE }} ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Push image
        run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Deploy
        run: |
          gcloud run deploy ${{ env.SERVICE }} --image ${{ env.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }} \
          --timeout 300 \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --set-env-vars PORT=8080 \
          --set-env-vars MONGODB_URI=$(printf %q "${{ secrets.MONGODB_URI }}") \
